board-arty: ["targets/arty", "platforms/arty.py"]
board-atlys: ["targets/atlys", "platforms/atlys.py"]
board-mimasv2: ["targets/mimasv2", "platforms/mimasv2.py"]
board-minispartan6: ["targets/minispartan6", "platforms/minispartan6.py"]
board-netv2: ["targets/netv2", "platforms/netv2.py"]
board-nexys-video: ["targets/nexys-video", "platforms/nexys-video.py"]
board-opsis: ["targets/opsis", "platforms/opsis.py", "platforms/tofe_*.py"]
board-pipstrello: ["targets/pipstrello", "platforms/pipstrello.py"]
boards-all: ["targets/common/"]
boards-artix7: ["targets/arty", "platforms/arty.py", "targets/netv2", "platforms/netv2.py", "targets/nexys-video", "platforms/nexys-video.py"]
boards-spartan6: ["targets/atlys", "platforms/atlys.py", "targets/mimasv2", "platforms/mimasv2.py", "targets/minispartan6", "platforms/minispartan6.py", "targets/opsis", "platforms/opsis.py", "targets/pipstrello", "platforms/pipstrello.py"]
firmware-fpga: ["gateware/"]
firmware-softcpu: ["firmware/"]
hdmi2ethernet: ["targets/*/net.py", "targets/*/hdmi2eth.py", "firmware/uip/", "third_party/libuip/"]
hdmi2usb: ["targets/*/hdmi2usb.py", "gateware/encoder/"]
hdmi2***: ["targets/*/base.py"]
level-docs: ["docs/", "README.md", "*.md"]
level-firmware: ["gateware/", "firmware/"]
level-infrastructure: [".travis.yml", ".travis/", "scripts/", ".github/"]
level-software: ["software/"]
